

# Enable vi mode
# set -o vi

# If not running interactively, don't do anythin
[[ $- != *i* ]] && return

# Disable ctrl-s & ctrl-q
stty -ixon

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

# Enable history appending instead of overwriting.
shopt -s histappend

# Set history size to infinite
HISTSIZE= HISTFILESIZE=

# change theme alias
alias spawn-mpd="$HOME/.config/mpd/spawn-mpd.sh"
alias network-connect="$HOME/.config/network/network-connect.sh"
alias update-mirrors="$HOME/.config/network/update-mirrors.sh"
alias vifm="$HOME/.config/vifm/scripts/vifm-run.sh"
alias change-theme="$HOME/.config/themes/change-theme.sh"
alias mirror-display="$HOME/.config/display/mirror-display.sh"
alias use-single-display="$HOME/.config/display/use-single-display.sh"
alias screen-detector="$HOME/.config/display/screen-detector.sh"
alias check-space="$HOME/.config/system/check-space.sh"
alias update-polybar-network-interface="$HOME/.config/themes/update-polybar-network-interface.sh"

PATH="$HOME/.local/bin:$HOME/bin:$PATH"
export PATH;

# execute neofetch depending on cols and lines in .bashrc
os=$(echo -n $(cat /etc/*-release 2> /dev/null | grep ^ID= | sed -e "s/ID=//"))
cols=$(tput cols)
lines=$(tput lines)
if [ "$cols" -gt 67 ] && [ "$lines" -gt 34 ];
then
  neofetch --config "$HOME/.config/neofetch/$os.conf"
fi

export EDITOR=vim

